const { Resend } = require('resend');

const sendSummaryEmail = async (toEmail, summary) => {
  const resend = new Resend(process.env.RESEND_API_KEY);

  const { data, error } = await resend.emails.send({
    from: 'Sales Insights <onboarding@resend.dev>',
    to: toEmail,
    subject: '📊 Your Sales Insight Report is Ready',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">
        <h2 style="color: #2563eb;">📊 Sales Insight Report</h2>
        <p>Hello,</p>
        <p>Your AI-generated sales summary is ready. Here is what our analysis found:</p>
        <hr />
        <div style="background: #f8fafc; padding: 20px; border-radius: 8px;">
          <pre style="white-space: pre-wrap; font-size: 14px;">${summary}</pre>
        </div>
        <hr />
        <p style="color: #64748b; font-size: 12px;">
          Generated by Sales Insight Automator | Rabbitt AI
        </p>
      </div>
    `,
  });

  if (error) {
    throw new Error(`Email sending failed: ${error.message}`);
  }

  return data;
};

module.exports = { sendSummaryEmail };